In [18]:
import pandas as pd
from sklearn.feature_selection import SelectKBest
from sklearn.model_selection import train_test_split
#Import chi2 for performing chi square test 
from sklearn.feature_selection import chi2

In [19]:
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('Campus Recruitment.csv')
# df = pd.read_csv('breast-cancer-wisconsin.csv',names=['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape', 'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin', 'Normal Nucleoli', 'Mitoses', 'Class'])
print(df.head())

Saving Campus Recruitment.csv to Campus Recruitment (2).csv
   sl_no gender  ssc_p    ssc_b  ...  specialisation  mba_p      status    salary
0      1      M  67.00   Others  ...          Mkt&HR  58.80      Placed  270000.0
1      2      M  79.33  Central  ...         Mkt&Fin  66.28      Placed  200000.0
2      3      M  65.00  Central  ...         Mkt&Fin  57.80      Placed  250000.0
3      4      M  56.00  Central  ...          Mkt&HR  59.43  Not Placed       NaN
4      5      M  85.80  Central  ...         Mkt&Fin  55.50      Placed  425000.0

[5 rows x 15 columns]


In [20]:
X = df[['sl_no','ssc_p','hsc_p','degree_p','etest_p','mba_p']]
Y = df['status']

X_train,X_test,Y_train,Y_test =  train_test_split(X,Y,test_size=0.2)
print(X_train.head())

     sl_no  ssc_p  hsc_p  degree_p  etest_p  mba_p
172    173   73.0  58.00     56.00    84.00  52.64
145    146   89.4  65.66     71.25    72.00  63.23
69      70   73.0  73.00     66.00    70.00  68.07
10      11   58.0  61.00     60.00    62.00  60.85
32      33   61.0  81.00     66.40    50.89  62.21


In [21]:
#UNIVARIATE FEATURE SELECTION
#Create array from data values
array = df.values

#Split the data into input and target
X = array[:,0:8]
Y = array[:,8]

#We will select the features using chi square
test = SelectKBest(score_func=chi2, k=4)



#Fit the function for ranking the features by score
fit = test.fit(X_train, Y_train)

#Summarize scores numpy.set_printoptions(precision=3) 
print(fit.scores_)

#Apply the transformation on to dataset
features = fit.transform(X_train)

#Summarize selected features 
print(features[0:5,:])

mask = test.get_support() #list of booleans for selected features
new_feat = [] 
for bool, feature in zip(mask, df.columns):
 if bool:
  new_feat.append(feature)
print('The best features are:{}'.format(new_feat))

[ 19.55173464 111.55805249  68.9239182   31.00684954   1.11471677
   0.83780377]
[[173.    73.    58.    56.  ]
 [146.    89.4   65.66  71.25]
 [ 70.    73.    73.    66.  ]
 [ 11.    58.    61.    60.  ]
 [ 33.    61.    81.    66.4 ]]
The best features are:['sl_no', 'gender', 'ssc_p', 'ssc_b']


In [22]:
#RECURSIVE FEATURE ELIMINATION
from sklearn.linear_model import LogisticRegression
from sklearn import feature_selection
model = LogisticRegression() 
rfe = feature_selection.RFE(model, 3)

fit = rfe.fit(X_train, Y_train)

print("Num Features: %d"% fit.n_features_)
print("Selected Features: %s"% fit.support_) 
print("Feature Ranking: %s"% fit.ranking_)

Num Features: 3
Selected Features: [False  True False  True False  True]
Feature Ranking: [4 1 2 1 3 1]


In [23]:
#PCA
from sklearn.decomposition import PCA
#Feature extraction
pca = PCA(n_components=3) 
fit = pca.fit(X_train)

#Summarize components
print("Explained Variance: %s" % fit.explained_variance_ratio_)

print(fit.components_)

Explained Variance: [0.88514916 0.05745585 0.03096901]
[[-0.99929014  0.01798711  0.02177969  0.01140628 -0.0221069  -0.00158389]
 [ 0.00751022  0.48288654  0.48531173  0.26660813  0.65700828  0.16881037]
 [-0.03606432 -0.44677148 -0.40711294 -0.23409664  0.75267682 -0.10968148]]
